config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'sales#index' 

  resource :mypage

  get 'item_sales/create'
  get 'item_sales/destroy'
  get 'stock_polishes/create'
  get 'stock_polishes/destroy'
  # get "/" => "home#top"


  resources :sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :farmers
  # resources :stocks
  resources :stocks do
    resource :stock_polishes, only: [:create, :destroy]
  end

  resources :polishes
  # resources :items
  resources :items do
    resource :item_sales, only: [:create, :destroy]
  end
  resources :cliants

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliant.rb
class Cliant < ApplicationRecord
    has_many :sales
end

app/models/farmer.rb
class Farmer < ApplicationRecord

    has_many :stocks

end

app/models/item.rb
class Item < ApplicationRecord


    has_many :item_sales
    has_many :sales, through: :item_sales

end

app/models/item_sale.rb
class ItemSale < ApplicationRecord
    
    belongs_to :sale
    belongs_to :item

end

app/models/polish.rb
class Polish < ApplicationRecord

    # # 使用した玄米の合計
    # def self.sumpolish  
    #     sum(:polish_amount_total)
    # end

    

    has_many :stock_polishes
    has_many :stocks, through: :stock_polishes
    
    has_many :sales

end

app/models/sale.rb
class Sale < ApplicationRecord

    belongs_to :polilsh,optional: true
    belongs_to :cliant,optional: true

    has_many :item_sales
    has_many :items, through: :item_sales
    

    validates :is_done, inclusion:{in: [true, false]}
    with_options presence: true do
        validates :seller_name
        validates :job_type
        validates :cliant_id
        validates :cliant_name
        validates :item_id
        validates :item_name
        validates :sale_item_count
        validates :sale_item_amount
        # validates :polish_id
    end

end

app/models/stock.rb
class Stock < ApplicationRecord

    # 仕入れの合計
    def self.sumstock  
        sum(:stock_purchased_amount)
        #Stock.sumでも可
      end

    # 使用した在庫の合計
      def self.sumusedstock  
        sum(:stock_used_amount)
      end

    # 現在個数
    def self.sumpresentstock  
        self.sumstock-self.sumusedstock
      end


    belongs_to :farmer

    has_many :stock_polishes
    has_many :polishes, through: :stock_polishes    
    
end

app/models/stock_polish.rb
class StockPolish < ApplicationRecord

    belongs_to :stock
    belongs_to :polish

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cliants_controller.rb
class CliantsController < ApplicationController

  before_action :authenticate_user!

    
  def index
    @cliants = Cliant.all.order('created_at DESC')
  end

  def new
    @cliant = Cliant.new
  end

  def create
    @cliant = Cliant.new(cliant_params)

    if @cliant.save
      redirect_to cliants_path
    else
      render 'new'
    end
  end


  def show
    @cliant = Cliant.find(params[:id])
  end


  def edit
    @cliant = Cliant.find(params[:id])
  end

  def update
    @cliant = Cliant.find(params[:id])

   if @cliant.update(cliant_params)
    redirect_to cliants_path
  else
    render 'edit'
  end
end

def destroy
  @cliant = Cliant.find(params[:id])

  @cliant.destroy
  redirect_to cliants_path
end

  private
  def cliant_params
    params.require(:cliant).permit(:user_id, :cliant_name, :cliant_officer, :cliant_email, :cliant_tel, :cliant_address, :cliant_map_latitude, :cliant_map_longitude, :cliant_map_code, :cliant_type, :cliant_start_trading, :cliant_memorandum, :cliant_delivery_type, :cliant_postage, :cliant_postage_memorandum, :cliant_total_sales_without_tax, :cliant_total_sales_tax_included)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!


  def index
    @items = Item.all.order('created_at DESC')
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end




  
  def show
    @item = Item.find(params[:id])
  end


  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end
  
  
  def destroy
    @item = Item.find(params[:id])

    @item.destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:user_id, :item_name, :item_price_without_tax, :item_price_tax_included, :item_memorandum, :item_shipment_total, :item_total_sales_without_tax, :item_total_sales_tax_included, :polish_id)
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :authenticate_user!

  before_action :ensure_correct_user,{only:[:edit,:update,:destroy]}
  def ensure_correct_user
    @sale = Sale.find_by(id:params[:id])
        if @sale.user_id != current_user.id
        flash[:notice] = "権限がありません"
        redirect_to sales_path
        end
    end

    def index
      @sales = Sale.all.order('created_at DESC')
      @sales_unFinished = Sale.where(:is_done => false ).order('created_at DESC')
      @sales_finished = Sale.where(:is_done => true ).order('created_at DESC')

      @sale = @sales.each.find(params[:id])
      logger.debug("sale --------------")
      logger.debug(@sale)

      # @polish = Polish.find(@sale[:polish_id])
      # @item = Item.find(@sale[:item_id])
      # @cliant = Cliant.find(@sale[:cliant_id])
      # @user = User.find(@sale[:user_id])
    end
  
    def new
      @sale = Sale.new
      @polishes = Polish.all.order('created_at DESC')
      @items = Item.all
      @cliants = Cliant.all
      @users = User.all
    end
  
    def show
      @sale = Sale.find(params[:id])
      
      @polish = Polish.find(@sale[:polish_id])
      @item = Item.find(@sale[:item_id])
      @cliant = Cliant.find(@sale[:cliant_id])
      @user = User.find_by(id: @sale.user_id)
    end
  
    def create
      @sale = Sale.new(sale_params)
      @sale.user_id = current_user.id

      if @sale.save
        redirect_to sales_path
      else
        render 'new'
      end
    end
  

    def destroy
      @sale = Sale.find(params[:id])
      @sale.destroy
      redirect_to sales_path, notice:"削除しました"
    end
  
    def edit
      @sale = Sale.find(params[:id])
      @polishes = Polish.all
      @items = Item.all
      @cliants = Cliant.all
      @users = User.all
    end
  
    def update
      @sale = Sale.find(params[:id])

        if is_done(params[:sale])
        end

      if @sale.update(sale_params)
        redirect_to sales_path, notice: "更新しました"
      else
        render 'edit'
      end
    end  

    def is_done(sale)
      castAfter = ActiveRecord::Type::Boolean.new.cast(sale[:is_done])
      logger.debug(castAfter)
    end


  def update_is_done
      @sale = Sale.find(params[:id])

    if  @sale.update(params[:id])
    end

    @sale.update_is_done
        redirect_to sales_path
        flash[:notice] = "Jobの状態が更新されました！"
  end


    private
    def sale_params
      params.require(:sale).permit(:user_id, :job_type, :cliant_name, :cliant_id, :material_infomation, :item_name, :sale_item_count, :sale_item_amount, :polish_id, :item_id, :sale_memorandum, :start_time, :sale_job_title, { :polish_ids=> [] }, :is_done, :seller_name)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cliants_helper.rb
module CliantsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_sales_helper.rb
module ItemSalesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/polishes_helper.rb
module PolishesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/cliants/edit.html.erb
<div class="container mb-5">

<%= form_with(model: @cliant, local: true) do |form| %>
  <% if @cliant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliant.errors.count, "error") %> prohibited this cliant from being saved:</h2>

      <ul>
      <% @cliant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>

<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 cliantsTitle">
    <div class="row">
      <div class="pageTitle col-sm-5">
      <h1>顧客情報の編集</h1>
      </div>
      
      <div class="newBtnBox col-sm-7 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to '顧客一覧へ戻る',  cliants_path %> 
      </button>
  </div>


  </div>
</div>

<div class="container">

<%= form_for(@cliant) do |f| %>
<div class="field">
  <%= f.label :顧客名 %><br>
  <%= f.text_field :cliant_name %>
</div>
<div class="field">
  <%= f.label :タイプ %><br>
  <%= f.text_field :cliant_type %>
</div>
<div class="field">
  <%= f.label :担当者 %><br>
  <%= f.text_field :cliant_officer %>
</div>
<div class="field">
  <%= f.label :メールアドレス %><br>
  <%= f.email_field :cliant_email %>
</div>
<div class="field">
  <%= f.label :電話番号 %><br>
  <%= f.text_field :cliant_tel %>
</div>
<div class="field">
  <%= f.label :備考 %><br>
  <%= f.text_area	 :cliant_memorandum %>
</div>
<div class="field">
  <%= f.label :配送区分 %><br>
  <%= f.text_field :cliant_delivery_type %>
</div>
<div class="field">
  <%= f.label :送料 %><br>
  <%= f.text_field :cliant_postage %>
</div>
<div class="field">
  <%= f.label :配送備考 %><br>
  <%= f.text_area	 :cliant_postage_memorandum %>
</div>
<div class="field">
  <%= f.label :住所 %><br>
  <%= f.text_field :cliant_address %>
</div>
<div class="field">
  <%= f.label :緯度 %><br>
  <%= f.text_field :cliant_map_latitude %>
</div>
<div class="field">
  <%= f.label :経度 %><br>
  <%= f.text_field :cliant_map_longitude %>
</div>
<div class="field">
  <%= f.label :gmapコード %><br>
  <%= f.text_field :cliant_map_code %>
</div>
<br>
<div class="actions">
  <%= f.submit "顧客情報を更新"%>
</div>
<% end %>


  </div>
</div>

app/views/cliants/index.html.erb
<div class="container">

  <div class="mainBox pb-3 shadow-sm">
    <div class="pageHeader container shadow-sm mb-4 cliantsTitle">
      <div class="row">
        <div class="pageTitle col-sm-3">
        <h1>顧客一覧</h1>
        </div>

        <div class="newBtnBox col-sm-8 text-right">
        <button class="newBtnCliants my-2">
        <%= link_to '新規顧客登録', new_cliant_path %>
        </button>
        </div>

        <div class="col-sm-1"></div>

      </div>
    </div>

 <div class="tableBox container">
    <table class="mx-auto">
      <thead>
        <tr>
          <th>ID</th>
          <th>顧客名</th>
          <th>担当者</th>
          <th>電話番号</th>
          <th>住所</th>
          <th>顧客タイプ</th>
          <th>備考</th>
          <th>配送区分</th>
        </tr>
      </thead>

      <tbody>
        <% @cliants.each do |cliant| %>
        <tr>
          <td><%=link_to cliant.id, cliant %></td>
          <td><%= cliant.cliant_name %></td>
          <td><%= cliant.cliant_officer %></td>
          <td><%= cliant.cliant_tel %></td>
          <td><%= cliant.cliant_address %></td>
          <td><%= cliant.cliant_type %></td>
          <td><%= cliant.cliant_memorandum %></td>
          <td><%= cliant.cliant_delivery_type %></td>

          <td class="showBtnBox"><button class="mx-1"><%= link_to "詳細", cliant %></button></td>
          <td class="editBtnBox"><button class="mx-1"><%= link_to "編集", edit_cliant_path(cliant) %></button></td>
          <td class="deleteBtnBox"><button class="mx-1"><%= link_to "削除",cliant ,method: :delete, data: {confirm: "削除します。この処理は取り消せません。"} %></button></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>

</div>

app/views/cliants/new.html.erb
<div class="container mb-5">


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 cliantsTitle">
    <div class="row">
      <div class="pageTitle col-sm-5">
      <h1>新規顧客の登録</h1>

      </div>
      
      <div class="newBtnBox col-sm-7 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to '顧客一覧へ戻る', cliants_path %>
      </button>
  </div>
  </div>
</div>

<div class="container">





<%= form_for(@cliant) do |f| %>
<div class="field">
  <%= f.label :顧客名 %><br>
  <%= f.text_field :cliant_name %>
</div>
<div class="field">
  <%= f.label :タイプ %><br>
  <%= f.text_field :cliant_type %>
</div>
<div class="field">
  <%= f.label :担当者 %><br>
  <%= f.text_field :cliant_officer %>
</div>
<div class="field">
  <%= f.label :メールアドレス %><br>
  <%= f.email_field :cliant_email %>
</div>
<div class="field">
  <%= f.label :電話番号 %><br>
  <%= f.text_field :cliant_tel %>
</div>
<div class="field">
  <%= f.label :備考 %><br>
  <%= f.text_area	 :cliant_memorandum %>
</div>
<div class="field">
  <%= f.label :配送区分 %><br>
  <%= f.text_field :cliant_delivery_type %>
</div>
<div class="field">
  <%= f.label :送料 %><br>
  <%= f.text_field :cliant_postage %>
</div>
<div class="field">
  <%= f.label :配送備考 %><br>
  <%= f.text_area	 :cliant_postage_memorandum %>
</div>
<div class="field">
  <%= f.label :住所 %><br>
  <%= f.text_field :cliant_address %>
</div>
<div class="field">
  <%= f.label :緯度 %><br>
  <%= f.text_field :cliant_map_latitude %>
</div>
<div class="field">
  <%= f.label :経度 %><br>
  <%= f.text_field :cliant_map_longitude %>
</div>
<div class="field">
  <%= f.label :gmapコード %><br>
  <%= f.text_field :cliant_map_code %>
</div>
<br>
<div class="actions">
  <%= f.submit "新規顧客を登録"%>
</div>
<% end %>

</div>
</div>

app/views/cliants/show.html.erb
<div class="container mb-5">
<p id="notice"><%= notice %></p>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 cliantsTitle">
    <div class="row">
      <div class="pageTitle col-sm-4">
      <h1>顧客　の詳細情報</h1>
      </div>

      <div class="newBtnBox col-sm-8 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to "顧客一覧へ戻る" , cliants_path%> 
      </button>
      <button class="newBtnSales m-2 ">
        <%= link_to "編集" , edit_cliant_path(@cliant) %> 
      </button>
      </div>
  </div>
</div>

<div class="container">

<p class="bg-light pl-2"> 顧客ID：<%= @cliant.id %> </p>

<h2> 顧客名：<%= @cliant.cliant_name %> </h2>
<p> 顧客タイプ：<%= @cliant.cliant_type %> </p>
<p> 担当者：<%= @cliant.cliant_officer %> </p>
<p> メールアドレス：<%= @cliant.cliant_email %> </p>
<p> 電話番号：<%= @cliant.cliant_tel %> </p>
<p> 取引開始時期：<%= @cliant.cliant_start_trading %> </p>
<p> 備考：<%= @cliant.cliant_memorandum %> </p>
<p> 配送区分：<%= @cliant.cliant_delivery_type %> </p>
<p> 送料：<%= @cliant.cliant_postage %> </p>
<p> 配送備考：<%= @cliant.cliant_postage_memorandum %> </p>
<p> 住所：<%= @cliant.cliant_address %> </p>
<p> 緯度：<%= @cliant.cliant_map_latitude %> </p>
<p> 経度：<%= @cliant.cliant_map_longitude %> </p>
<p> gmap：<%= @cliant.cliant_map_code %> </p>
<p> 累計売上（税別）：<%= @cliant.cliant_total_sales_without_tax %> </p>
<p> 累計売上（税込み）：<%= @cliant.cliant_total_sales_tax_included %> </p>


  </div>
</div>