config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'sales#index' 

  resource :mypage

  get 'item_sales/create'
  get 'item_sales/destroy'
  get 'stock_polishes/create'
  get 'stock_polishes/destroy'
  # get "/" => "home#top"


  resources :sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :farmers
  # resources :stocks
  resources :stocks do
    resource :stock_polishes, only: [:create, :destroy]
  end

  resources :polishes
  # resources :items
  resources :items do
    resource :item_sales, only: [:create, :destroy]
  end
  resources :cliants

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliant.rb
class Cliant < ApplicationRecord
    has_many :sales
end

app/models/farmer.rb
class Farmer < ApplicationRecord

    has_many :stocks

end

app/models/item.rb
class Item < ApplicationRecord


    has_many :item_sales
    has_many :sales, through: :item_sales

end

app/models/item_sale.rb
class ItemSale < ApplicationRecord
    
    belongs_to :sale
    belongs_to :item

end

app/models/polish.rb
class Polish < ApplicationRecord

    # # 使用した玄米の合計
    # def self.sumpolish  
    #     sum(:polish_amount_total)
    # end

    

    has_many :stock_polishes
    has_many :stocks, through: :stock_polishes
    
    has_many :sales

end

app/models/sale.rb
class Sale < ApplicationRecord

    belongs_to :polilsh,optional: true
    belongs_to :cliant,optional: true

    has_many :item_sales
    has_many :items, through: :item_sales
    

    validates :is_done, inclusion:{in: [true, false]}
    with_options presence: true do
        validates :seller_name
        validates :job_type
        validates :cliant_id
        validates :cliant_name
        validates :item_id
        validates :item_name
        validates :sale_item_count
        validates :sale_item_amount
        # validates :polish_id
    end

end

app/models/stock.rb
class Stock < ApplicationRecord

    # 仕入れの合計
    def self.sumstock  
        sum(:stock_purchased_amount)
        #Stock.sumでも可
      end

    # 使用した在庫の合計
      def self.sumusedstock  
        sum(:stock_used_amount)
      end

    # 現在個数
    def self.sumpresentstock  
        self.sumstock-self.sumusedstock
      end


    belongs_to :farmer

    has_many :stock_polishes
    has_many :polishes, through: :stock_polishes    
    
end

app/models/stock_polish.rb
class StockPolish < ApplicationRecord

    belongs_to :stock
    belongs_to :polish

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!


  def index
    @items = Item.all.order('created_at DESC')
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end




  
  def show
    @item = Item.find(params[:id])
  end


  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end
  
  
  def destroy
    @item = Item.find(params[:id])

    @item.destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:user_id, :item_name, :item_price_without_tax, :item_price_tax_included, :item_memorandum, :item_shipment_total, :item_total_sales_without_tax, :item_total_sales_tax_included, :polish_id)
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :authenticate_user!

  before_action :ensure_correct_user,{only:[:edit,:update,:destroy]}
  def ensure_correct_user
    @sale = Sale.find_by(id:params[:id])
        if @sale.user_id != current_user.id
        flash[:notice] = "権限がありません"
        redirect_to sales_path
        end
    end

    def index
      @sales = Sale.all.order('created_at DESC')
      @sales_unFinished = Sale.where(:is_done => false ).order('created_at DESC')
      @sales_finished = Sale.where(:is_done => true ).order('created_at DESC')

      @sale = @sales.each.find(params[:id])
      logger.debug("sale --------------")
      logger.debug(@sale)

      # @polish = Polish.find(@sale[:polish_id])
      # @item = Item.find(@sale[:item_id])
      # @cliant = Cliant.find(@sale[:cliant_id])
      # @user = User.find(@sale[:user_id])
    end
  
    def new
      @sale = Sale.new
      @polishes = Polish.all.order('created_at DESC')
      @items = Item.all
      @cliants = Cliant.all
      @users = User.all
    end
  
    def show
      @sale = Sale.find(params[:id])
      
      @polish = Polish.find(@sale[:polish_id])
      @item = Item.find(@sale[:item_id])
      @cliant = Cliant.find(@sale[:cliant_id])
      @user = User.find_by(id: @sale.user_id)
    end
  
    def create
      @sale = Sale.new(sale_params)
      @sale.user_id = current_user.id

      if @sale.save
        redirect_to sales_path
      else
        render 'new'
      end
    end
  

    def destroy
      @sale = Sale.find(params[:id])
      @sale.destroy
      redirect_to sales_path, notice:"削除しました"
    end
  
    def edit
      @sale = Sale.find(params[:id])
      @polishes = Polish.all
      @items = Item.all
      @cliants = Cliant.all
      @users = User.all
    end
  
    def update
      @sale = Sale.find(params[:id])

        if is_done(params[:sale])
        end

      if @sale.update(sale_params)
        redirect_to sales_path, notice: "更新しました"
      else
        render 'edit'
      end
    end  

    def is_done(sale)
      castAfter = ActiveRecord::Type::Boolean.new.cast(sale[:is_done])
      logger.debug(castAfter)
    end


  def update_is_done
      @sale = Sale.find(params[:id])

    if  @sale.update(params[:id])
    end

    @sale.update_is_done
        redirect_to sales_path
        flash[:notice] = "Jobの状態が更新されました！"
  end


    private
    def sale_params
      params.require(:sale).permit(:user_id, :job_type, :cliant_name, :cliant_id, :material_infomation, :item_name, :sale_item_count, :sale_item_amount, :polish_id, :item_id, :sale_memorandum, :start_time, :sale_job_title, { :polish_ids=> [] }, :is_done, :seller_name)
    end

  end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  before_action :authenticate_user!


    def index
        @stocks = Stock.all.order('created_at DESC')

        @farmer = Farmer.find_by(params[:id])


    end
    
    def new
        @stock = Stock.new
        @farmers = Farmer.all
      end
    
      def create
        @stock = Stock.new(stock_params)

        if @stock.save
          redirect_to stocks_path
        else
          render 'new'
        end
      end
    
      
      def show
        @stock = Stock.find(params[:id])
        # @farmer = Farmer.find_by(params[:id])
        @farmer = Farmer.find(@stock[:farmer_id])

      end



      def edit
        @stock = Stock.find(params[:id])
        @farmers = Farmer.all

      end

      def update
        @stock = Stock.find(params[:id]) 

        if @stock.update(stock_params)
          redirect_to stocks_path
        else
          render 'edit'
        end
      end


      def destroy
        @stock = Stock.find(params[:id])
    
        @stock.destroy
        redirect_to stocks_path
      end
      
      private
      def stock_params
        params.require(:stock).permit(:user_id, :polish_id, :stock_farmer_name, :farmer_id, :stock_brand, :stock_purchased_amount, :stock_used_amount, :stock_present_amount, :stock_price_without_tax, :stock_price_tax_included, :stock_quality, :stock_memorandum, :stock_arrivalday)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cliants_helper.rb
module CliantsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_sales_helper.rb
module ItemSalesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/polishes_helper.rb
module PolishesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/items/edit.html.erb
<div class="container mb-5">


<%= form_with(model: @item, local: true) do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 itemsTitle">
    <div class="row">
      <div class="pageTitle col-sm-5">
      <h1 class="itemsH1">商品情報の編集</h1>

      </div>
      
      <div class="newBtnBox col-sm-7 text-right">
      <button class="newBtnSales m-2 ">
      <%= link_to '商品一覧へ戻る', items_path %>
      </button>
  </div>

  </div>
</div>

<div class="container">




<%= form_for(@item) do |f| %>
<div class="field">
  <%= f.label :商品名 %><br>
  <%= f.text_field :item_name %>
</div>
<div class="field">
  <%= f.label :単価（税別） %><br>
  <%= f.text_field :item_price_without_tax %>
</div>
<div class="field">
  <%= f.label :備考 %><br>
  <%= f.text_area :item_memorandum %>
</div>
<br>
<div class="actions">
  <%= f.submit "商品情報を編集"%>
</div>
<% end %>


</div>
</div>

app/views/items/index.html.erb
<div class="container">

  <div class="mainBox pb-3 shadow-sm">
    <div class="pageHeader container shadow-sm mb-4 itemsTitle">
      <div class="row">
        <div class="pageTitle col-sm-3">
        <h1 class="itemsH1">商品 一覧</h1>
        </div>

        <div class="newBtnBox col-sm-8 text-right">
        <button class="newBtnItems my-2">
        <%= link_to '新規商品 登録', new_item_path %>
        </button>
        </div>

        <div class="col-sm-1"></div>

      </div>
    </div>
 <div class="tableBox container">
    <table class="mx-auto">
      <thead>
        <tr>
          <th>ID</th>
          <th>商品名</th>
          <th>単価<br>（税別）</th>
          <th>備考</th>
          <th>累計出荷数</th>
          <th>累計売上高<br>（税別）</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%=link_to item.id, item %></td>
          <td><%= item.item_name %></td>
          <td><%= "#{item.item_price_without_tax}円" %></td>
          <td><%= item.item_memorandum %></td>
          <td><%= item.item_shipment_total %></td>
          <td><%= item.item_total_sales_without_tax %></td>

          <td class="showBtnBox"><button class="mx-1"><%= link_to "詳細", item %></button></td>
          <td class="editBtnBox"><button class="mx-1"><%= link_to "編集", edit_item_path(item) %></button></td>
          <td class="deleteBtnBox"><button class="mx-1"><%= link_to "削除", item ,method: :delete, data: {confirm: "削除します。この処理は取り消せません。"} %></button></td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>
</div>


</div>

app/views/items/new.html.erb
<div class="container mb-5">


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 itemsTitle">
    <div class="row">
      <div class="pageTitle col-sm-5">
      <h1 class="itemsH1">新規商品の登録</h1>

      </div>
      
      <div class="newBtnBox col-sm-7 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to '商品一覧へ戻る', items_path %>

      </button>
  </div>
  </div>
</div>

<div class="container">


<%= form_for(@item) do |f| %>
<div class="field">
  <%= f.label :商品名 %><br>
  <%= f.text_field :item_name %>
</div>
<div class="field">
  <%= f.label :単価（税別） %><br>
  <%= f.text_field :item_price_without_tax %>
</div>
<div class="field">
  <%= f.label :備考 %><br>
  <%= f.text_area :item_memorandum %>
</div>
<br>
<div class="actions">
  <%= f.submit "新規商品を登録"%>
</div>
<% end %>


</div>
</div>

app/views/items/show.html.erb
<div class="container mb-5">
<p id="notice"><%= notice %></p>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 itemsTitle">
    <div class="row">
      <div class="pageTitle col-sm-4">
      <h1 class="itemsH1">商品　の詳細情報</h1>
      </div>

      <div class="newBtnBox col-sm-8 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to "商品一覧へ戻る" , items_path%>
      </button>
      <button class="newBtnSales m-2 ">
        <%= link_to "編集" , edit_item_path(@item) %> 
      </button>
      </div>
  </div>
</div>

<div class="container">


<p class="bg-light pl-2"> 商品ID：<%= @item.id %> </p>
<h2> 商品名：<%= @item.item_name %> </h2>
<p> 単価（税別）：<%= @item.item_price_without_tax %> </p>
<p> 単価（税込み：8％）：<%= (@item.item_price_without_tax*1.08).floor %> </p>
<p> 備考：<%= @item.item_memorandum %> </p>
<p> 累計出荷数：<%= @item.item_shipment_total %> </p>
<p> 累計売上（税別）：<%= @item.item_total_sales_without_tax %> </p>
<p> 累計売上（税込み：8％）：<%= @item.item_total_sales_tax_included %> </p>

  </div>
</div>

app/views/sales/edit.html.erb
<div class="container mb-5">


<%= form_with(model: @sale, local: true) do |form| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 salesTitle">
    <div class="row">
      <div class="pageTitle col-sm-5">
      <h1>登録Jobの編集</h1>
      </div>
      
      <div class="newBtnBox col-sm-7 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to 'Job一覧へ戻る', sales_path %> 
      </button>
  </div>

  </div>
</div>

<div class="container">


<%= form_for(@sale) do |f| %>

  <div class="field">
    <%= f.label :入力者id（要修正：ここはdeviseを入れてcurrent_user_idで取得） %> 
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :納品日 %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :納品者id %>
    <%= f.collection_select(:seller_name, @users, :id, :email, {prompt: "納品者を選択"} ) %>
  </div>
  
  <div class="field">
    <%= f.label :ジョブ %>
    <%= f.select :job_type, [ ["配達","配達"], ["郵送","郵送"], ["店頭渡し", "店頭渡し" ]], prompt: "納品形態を選択してください" %>
  </div>

  <div class="field">
  <%= f.label :顧客id %>
  <%= f.collection_select(:cliant_id, @cliants, :id, :cliant_name, {prompt: "顧客名を選択"} ) %>
</div>


  <div class="field">
    <%= f.label :商品id %>
    <%= f.collection_select(:item_id, @items, :id, :item_name, {prompt: "商品idを選択"} ) %>
  </div>

  <div class="field">
    <%= f.label :商品名 %>
    <%= f.collection_select(:item_name, @items, :item_name, :item_name, {prompt: "商品idと同じ名称を選択"} ) %>
  </div>



  <div class="field">
    <%= f.label :納品数（個） %>
    <%= f.number_field :sale_item_count %>
  </div>

  <div class="field">
    <%= f.label :合計重量（kg） %>
    <%= f.number_field :sale_item_amount %>
  </div>

  <div class="field">
    <%= f.label :精米id %>
    <%= f.collection_select(:polish_id, @polishes, :id, :polish_day, {prompt: "使用する精米を選択"} ) %>
  </div>

  <div class="field">
    <%= f.label :備考・メモ %>
    <%= f.text_area :sale_memorandum %>
  </div>

  <div class="field">
    <%= f.label :is_done, "完了したらチェックする" %><br>
    <%= f.check_box :is_done %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


</div>
</div>

app/views/sales/index.html.erb
<div class="container">


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 salesTitle">
    <div class="row">
      <div class="pageTitle col-sm-3">
      <h1>Job一覧</h1>
      </div>

      <div class="newBtnBox col-sm-8 text-right">
      <button class="newBtnSales my-2">
      <%= link_to '新規Job作成', new_sale_path %>
      </button>
      </div>
      <div class="col-sm-1"></div>
  </div>
</div>

 <div class="tableBox container">
    <table class="mx-auto">
      <thead>
        <tr>
          <th>ID</th>
          <th>納品日</th>
          <th>Job</th>
          <th>顧客名</th>
          <th>商品名</th>
          <th>納品数 <br>（個）</th>
          <th>合計重量 <br>（kg）</th>
          <th>備考・メモ</th>
        </tr>
      </thead>

      <tbody>
        <% @sales_unFinished.each do |sale| %>
          <tr>
            <td class="px-1"><%= link_to sale.id, sale %></td>
            <td><%= sale.start_time.strftime("%m月%d日") %></td>
            <td><%= sale.job_type %></td>
            <td><%= sale.cliant_name %></td>
            <td><%= sale.item_name %></td>
            <td><%= "#{sale.sale_item_count}個" %></td>
            <td><%= "#{sale.sale_item_amount} kg" %></td>
            <td><%= sale.sale_memorandum %></td>

            <td class="showBtnBox"><button class="mx-1"><%= link_to '詳細', sale %></button></td>
        <% if current_user.id == sale.user_id %>
            <td class="editBtnBox"><button class="mx-1"><%= link_to '編集', edit_sale_path(sale) %></button></td>
            <td class="deleteBtnBox"><button class="mx-1"><%= link_to '削除', sale, method: :delete, data: { confirm: '削除します。この処理は取り消せません。' } %></button></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    <hr>
 </div>
</div>

<br>


<hr class="shadow-sm">
<div class="container mb-5">

<%= month_calendar events: @sales do |date, sales| %>
    <%= date.strftime("\n%m月%d日") %>

  <% sales.each do |sale| %>
    <div>
    <% if sale.is_done == false %>
      <div class="bg-warning">
        <%= link_to "●#{sale.job_type}", sale %>
        <%= link_to sale.cliant_name, sale %>
      </div>
    <% else %>
      <div>
        <%= link_to "●#{sale.job_type}", sale ,class:"text-dark" %>
        <%= link_to sale.cliant_name, sale ,class:"text-dark" %>
      </div>
    <% end %>
    </div>
  <% end %>
<% end %>
<p>※背景がオレンジ色の項目は未完了Job</p>

</div>

</div>

app/views/sales/show.html.erb
<div class="container mb-5">
<p id="notice"><%= notice %></p>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 salesTitle">
    <div class="row">
      <div class="pageTitle col-sm-4">
      <h1>登録Jobの詳細</h1>
      </div>

      <div class="newBtnBox col-sm-8 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to 'Job一覧へ戻る', sales_path %> 
      </button>

      <% if current_user.id == @sale.user_id %>
        <button class="newBtnSales m-2 ">
          <%= link_to "編集" , edit_sale_path(@sale) %> 
        </button>
      <% end %>

      </div>
  </div>
</div>

<div class="container">
<p class="bg-light pl-2"> Job ID：<%= @sale.id %> </p>

<div>完了フラグ：
    <% if @sale.is_done == false %>
    <p class="text-danger">未完了</p>
    <% else %>
    <p class="text-primary">完了済み</p>
    <% end %>
</div>

<p>
  <strong>入力者id：</strong>
  <%= @sale.user_id %>
</p>

<p>
  <strong>納品日:</strong>
  <%= @sale.start_time %>
</p>


<p>
  <strong>納品者id:</strong>
  <%= @sale.seller_name %>
</p>

<p>
  <strong>ジョブ:</strong>
  <%= @sale.job_type %>
</p>

<p>
  <strong>顧客id:</strong>
  <%=link_to @sale.cliant_id, @cliant %>
</p>

<p>
  <strong>顧客名:</strong>
  <%= link_to @cliant.cliant_name, @cliant %>
</p>


<p>
  <strong>商品id:</strong>
  <%= link_to @sale.item_id, @item %>
</p>

<p>
  <strong>商品名:</strong>
  <%= link_to @item.item_name, @item %>
</p>

<p>
  <strong>納品数:</strong>
  <%= @sale.sale_item_count %>
  <strong>個</strong>
</p>

<p>
  <strong>合計重量:</strong>
  <%= @sale.sale_item_amount %>
  <strong>kg</strong>
</p>

<p>
  <strong>精米情報:</strong>
  <%= link_to @polish.polish_day, @polish %>

</p>

<p>
  <strong>備考・メモ:</strong><br>
  <textarea name="" id="" cols="30" rows="3">
  <%= @sale.sale_memorandum %>
  </textarea>
</p>
</div>

</div>

app/views/stocks/index.html.erb
<div class="container">

  <div class="mainBox pb-3 shadow-sm">
    <div class="pageHeader container shadow-sm mb-4 stocksTitle">
      <div class="row">
        <div class="pageTitle col-sm-3">
        <h1>在庫一覧</h1>
        </div>

        <div class="pageTitle col-sm-3 my-auto">
        <h5 class="my-auto bg-light text-center">仕入れ合計：<%= Stock.sumstock %>袋</h5>
        </div>




        <div class="newBtnBox col-sm-3 text-right">
        <button class="newBtnStocks my-2">
        <%= link_to '新規在庫（仕入れ）登録', new_stock_path %>
        </button>
        </div>

        <div class="col-sm-1"></div>

      </div>
    </div>
  
  <div class="tableBox container">
  <table class="mx-auto">
    <thead>
      <tr>
        <th>ID</th>
        <th>入荷日</th>
        <th>銘柄</th>
        <th>仕入れ量（袋）</th>
        <th>使用数（袋）</th>
        <th>現在庫</th>
        <th>品質</th>
        <th>備考</th>
      </tr>
    </thead>

    <tbody>
      <% @stocks.each do |stock| %>
      <tr>
        <td><%=link_to stock.id, stock %></td>
        <td><%= stock.stock_arrivalday.strftime("%m月%d日") %></td>
        <td><%= stock.stock_brand %></td>
        <td><%= "#{stock.stock_purchased_amount} 袋" %></td>
        <td><%= "#{stock.stock_used_amount} 袋" %></td>
        <td><%= "#{stock.stock_present_amount} 袋" %></td>
        <td><%= stock.stock_quality %></td>
        <td><%= stock.stock_memorandum %></td>
        
        <td class="showBtnBox"><button class="mx-1"><%= link_to "詳細", stock %></button></td>
        <td class="editBtnBox"><button class="mx-1"><%= link_to "編集", edit_stock_path(stock) %></button></td>
        <td class="deleteBtnBox"><button class="mx-1"><%= link_to "削除", stock ,method: :delete, data: {confirm: "削除します。この処理は取り消せません。"} %></button></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div> 
  </div>


</div>

app/views/stocks/show.html.erb
<div class="container mb-5">
<p id="notice"><%= notice %></p>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 stocksTitle">
    <div class="row">
      <div class="pageTitle col-sm-4">
      <h1>在庫　の詳細情報</h1>

      </div>

      <div class="newBtnBox col-sm-8 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to '在庫一覧へ戻る', stocks_path %> 
      </button>
      <button class="newBtnSales m-2 ">
        <%= link_to "編集" , edit_stock_path(@stock) %> 
      </button>
      </div>
  </div>
</div>

<div class="container">

<p class="bg-light pl-2"> 在庫ID：<%= @stock.id %> </p>
<h2> 入荷日：<%= @stock.stock_arrivalday.strftime("%m月%d日")  %> </h2>

<p> 生産者ID：<%= link_to @stock.farmer_id, @farmer %> </p>
<p> 生産者：<%= @stock.farmer.farmer_name %> </p>
<p> 銘柄：<%= @stock.stock_brand %> </p>
<p> 仕入れ量（袋）：<%= "#{@stock.stock_purchased_amount} 袋" %> </p>
<p> 仕入れ単価（税別）：<%= "#{@stock.stock_price_without_tax} 円" %> </p>
<p> 仕入れ単価（税込み：８％）：<%= "#{@stock.stock_price_tax_included} 円" %> </p>

<p> 品質：<%= @stock.stock_quality %> </p>
<p> 備考：<%= @stock.stock_memorandum %> </p>
<hr>
<p> メールアドレス：<%= @stock.farmer.farmer_email %> </p>
<p> 電話番号：<%= @stock.farmer.farmer_tel %>  </p>
<p> 住所： <%= @stock.farmer.farmer_address %> </p>
<p> 緯度： <%= @stock.farmer.farmer_map_latitude %> </p>
<p> 経度： <%= @stock.farmer.farmer_map_longitude %> </p>
<p> gmap： <%= @stock.farmer.farmer_map_code %> </p>

  </div>
</div>