config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'sales#index' 

  resource :mypage

  get 'item_sales/create'
  get 'item_sales/destroy'
  get 'stock_polishes/create'
  get 'stock_polishes/destroy'
  # get "/" => "home#top"


  resources :sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :farmers
  # resources :stocks
  resources :stocks do
    resource :stock_polishes, only: [:create, :destroy]
  end

  resources :polishes
  # resources :items
  resources :items do
    resource :item_sales, only: [:create, :destroy]
  end
  resources :cliants

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliant.rb
class Cliant < ApplicationRecord
    has_many :sales
end

app/models/farmer.rb
class Farmer < ApplicationRecord

    has_many :stocks

end

app/models/item.rb
class Item < ApplicationRecord


    has_many :item_sales
    has_many :sales, through: :item_sales

end

app/models/item_sale.rb
class ItemSale < ApplicationRecord
    
    belongs_to :sale
    belongs_to :item

end

app/models/polish.rb
class Polish < ApplicationRecord

    # # 使用した玄米の合計
    # def self.sumpolish  
    #     sum(:polish_amount_total)
    # end

    

    has_many :stock_polishes
    has_many :stocks, through: :stock_polishes
    
    has_many :sales

end

app/models/sale.rb
class Sale < ApplicationRecord

    belongs_to :polilsh,optional: true
    belongs_to :cliant,optional: true

    has_many :item_sales
    has_many :items, through: :item_sales
    

    validates :is_done, inclusion:{in: [true, false]}
    with_options presence: true do
        validates :seller_name
        validates :job_type
        validates :cliant_id
        validates :cliant_name
        validates :item_id
        validates :item_name
        validates :sale_item_count
        validates :sale_item_amount
        # validates :polish_id
    end

end

app/models/stock.rb
class Stock < ApplicationRecord

    # 仕入れの合計
    def self.sumstock  
        sum(:stock_purchased_amount)
        #Stock.sumでも可
      end

    # 使用した在庫の合計
      def self.sumusedstock  
        sum(:stock_used_amount)
      end

    # 現在個数
    def self.sumpresentstock  
        self.sumstock-self.sumusedstock
      end


    belongs_to :farmer

    has_many :stock_polishes
    has_many :polishes, through: :stock_polishes    
    
end

app/models/stock_polish.rb
class StockPolish < ApplicationRecord

    belongs_to :stock
    belongs_to :polish

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!


  def index
    @items = Item.all.order('created_at DESC')
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end




  
  def show
    @item = Item.find(params[:id])
  end


  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end
  
  
  def destroy
    @item = Item.find(params[:id])

    @item.destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:user_id, :item_name, :item_price_without_tax, :item_price_tax_included, :item_memorandum, :item_shipment_total, :item_total_sales_without_tax, :item_total_sales_tax_included, :polish_id)
  end

end

app/controllers/polishes_controller.rb
class PolishesController < ApplicationController

  before_action :authenticate_user!


  def index
    @polishes = Polish.all.order('created_at DESC')

    # @stock = Stock.find_by(params[:id])
  end


  def new
    @polish = Polish.new
    @stocks = Stock.all
  end

  def create
    @polish = Polish.new(polish_params)

    if @polish.save
      redirect_to polishes_path
    else
      render 'new'
    end
  end

  def show
    @polish = Polish.find(params[:id])

    # @stock = Stock.find_by(params[:id])
    @stock = Stock.find(@polish[:id])



  end


  def edit
    @polish = Polish.find(params[:id])

    @stocks = Stock.all
  end

  def update
    @polish = Polish.find(params[:id])

    if @polish.update(polish_params)
      redirect_to polishes_path
    else
      render 'edit'
    end
  end
  

  def destroy
    @polish = Polish.find(params[:id])

    @polish.destroy
    redirect_to polishes_path
  end
  
  private
  def polish_params
    params.require(:polish).permit(:user_id, :polish_amount_total, :farmer_id, :polish_1_farmer_id, :polish_1_farmer, :polish_2_farmer_id, :polish_2_farmer, :polish_3_farmer_id, :polish_3_farmer, :polish_4_farmer_id, :polish_4_farmer, :polish_5_farmer_id, :polish_5_farmer, :polish_memorandum, :polish_1_brand, :polish_2_brand, :polish_3_brand, :polish_4_brand, :polish_5_brand, :polish_1_amount, :polish_2_amount, :polish_3_amount, :polish_4_amount, :polish_5_amount, :polish_day, :stock_id, :stock_brand, { :stock_ids=> [] })
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :authenticate_user!

  before_action :ensure_correct_user,{only:[:edit,:update,:destroy]}
  def ensure_correct_user
    @sale = Sale.find_by(id:params[:id])
        if @sale.user_id != current_user.id
        flash[:notice] = "権限がありません"
        redirect_to sales_path
        end
    end

    def index
      @sales = Sale.all.order('created_at DESC')
      @sales_unFinished = Sale.where(:is_done => false ).order('created_at DESC')
      @sales_finished = Sale.where(:is_done => true ).order('created_at DESC')

      @sale = @sales.each.find(params[:id])
      logger.debug("sale --------------")
      logger.debug(@sale)

      # @polish = Polish.find(@sale[:polish_id])
      # @item = Item.find(@sale[:item_id])
      # @cliant = Cliant.find(@sale[:cliant_id])
      # @user = User.find(@sale[:user_id])
    end
  
    def new
      @sale = Sale.new
      @polishes = Polish.all.order('created_at DESC')
      @items = Item.all
      @cliants = Cliant.all
      @users = User.all
    end
  
    def show
      @sale = Sale.find(params[:id])
      
      @polish = Polish.find(@sale[:polish_id])
      @item = Item.find(@sale[:item_id])
      @cliant = Cliant.find(@sale[:cliant_id])
      @user = User.find_by(id: @sale.user_id)
    end
  
    def create
      @sale = Sale.new(sale_params)
      @sale.user_id = current_user.id

      if @sale.save
        redirect_to sales_path
      else
        render 'new'
      end
    end
  

    def destroy
      @sale = Sale.find(params[:id])
      @sale.destroy
      redirect_to sales_path, notice:"削除しました"
    end
  
    def edit
      @sale = Sale.find(params[:id])
      @polishes = Polish.all
      @items = Item.all
      @cliants = Cliant.all
      @users = User.all
    end
  
    def update
      @sale = Sale.find(params[:id])

        if is_done(params[:sale])
        end

      if @sale.update(sale_params)
        redirect_to sales_path, notice: "更新しました"
      else
        render 'edit'
      end
    end  

    def is_done(sale)
      castAfter = ActiveRecord::Type::Boolean.new.cast(sale[:is_done])
      logger.debug(castAfter)
    end


  def update_is_done
      @sale = Sale.find(params[:id])

    if  @sale.update(params[:id])
    end

    @sale.update_is_done
        redirect_to sales_path
        flash[:notice] = "Jobの状態が更新されました！"
  end


    private
    def sale_params
      params.require(:sale).permit(:user_id, :job_type, :cliant_name, :cliant_id, :material_infomation, :item_name, :sale_item_count, :sale_item_amount, :polish_id, :item_id, :sale_memorandum, :start_time, :sale_job_title, { :polish_ids=> [] }, :is_done, :seller_name)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cliants_helper.rb
module CliantsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_sales_helper.rb
module ItemSalesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/polishes_helper.rb
module PolishesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/polishes/edit.html.erb
<div class="container mb-5">


<%= form_with(model: @polish, local: true) do |form| %>
  <% if @polish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@polish.errors.count, "error") %> prohibited this polish from being saved:</h2>

      <ul>
      <% @polish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 polishesTitle">
    <div class="row">
      <div class="pageTitle col-sm-5">
      <h1>精米情報の編集</h1>
  </div>

      <div class="newBtnBox col-sm-7 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to '精米一覧へ戻る', polishes_path %> 
      </button>
  </div>

</div>
  </div>


<div class="container">

<%= form_for(@polish) do |f| %>
  <div class="field">
    <%= f.label :精米日 %><br>
    <%= f.datetime_select :polish_day %>

  </div>
    <div class="field">
    <%= f.label :精米数（袋） %><br>
      <%= f.number_field :polish_amount_total, :step => 0.5 %>
  </div>
  <div class="field">
    <%= f.label :メモ（玄米で出荷する場合はこちらに“玄米”と記入） %><br>
    <%= f.text_area :polish_memorandum %>
  </div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>内訳−１</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_1_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_1_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_1_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_1_amount, :step => 0.5 %>
    </div>
    </div>
    <div class="col-sm-4">
      <h3>内訳−２</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_2_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_2_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_2_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_2_amount, :step => 0.5 %>
    </div>

    </div>
    <div class="col-sm-4">
      <h3>内訳−３</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_3_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_3_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_3_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_3_amount, :step => 0.5 %>
    </div>
    </div>
  </div>
</div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-sm-4 px-3">
      <h3>内訳−４</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_4_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_4_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_4_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_4_amount, :step => 0.5 %>
    </div>
    </div>
    <div class="col-sm-4 px-3">
      <h3>内訳−５</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_5_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_5_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_5_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_5_amount, :step => 0.5 %>
    </div>

    </div>
    <div class="col-sm-4 px-3">
    </div>
  </div>
</div>


<br>
<div class="actions">
  <%= f.submit "精米情報を更新"%>
</div>
<% end %>


</div>

app/views/polishes/index.html.erb
<div class="container">

<p class="time-limit" id="notice"><%= notice %></p>
  <div class="mainBox pb-3 shadow-sm">
    <div class="pageHeader container shadow-sm mb-4 polishesTitle">
      <div class="row">
        <div class="pageTitle col-sm-3">
        <h1>精米 一覧</h1>
        </div>


        <div class="newBtnBox col-sm-6 text-right">
        <button class="newBtnPolishes my-2">
        <%= link_to '新規精米登録', new_polish_path %>
        </button>
        </div>

        <div class="col-sm-1"></div>

      </div>
    </div>

 <div class="tableBox container">
    <table class="mx-auto">
      <thead>
        <tr>
          <th>ID</th>
          <th>精米日</th>
          <th class="bg-primary">合計精米量（袋）</th>
          <th>内訳-1</th>
          <th>使用量（袋）</th>
          <th>内訳-2</th>
          <th>使用量（袋）</th>
          <th>内訳-3</th>
          <th>使用量（袋）</th>
          <th>内訳-4</th>
          <th>使用量（袋）</th>
          <th>内訳-5</th>
          <th>使用量（袋）</th>
          <th>メモ</th>

        </tr>
      </thead>

      <tbody>
        <% @polishes.each do |polish| %>
        <tr>
          <td><%=link_to polish.id, polish %></td>
          <td><%= polish.polish_day.strftime("%m月%d日") %></td>
          <td class="strong bg-info" style="font-size:24px"><%= polish.polish_amount_total %></td>
          <td><%= polish.polish_1_farmer %></td>
          <td><%= polish.polish_1_amount %></td>
          <td><%= polish.polish_2_farmer %></td>
          <td><%= polish.polish_2_amount %></td>
          <td><%= polish.polish_3_farmer %></td>
          <td><%= polish.polish_3_amount %></td>
          <td><%= polish.polish_4_farmer %></td>
          <td><%= polish.polish_4_amount %></td>
          <td><%= polish.polish_5_farmer %></td>
          <td><%= polish.polish_5_amount %></td>
          <td><%= polish.polish_memorandum %></td>

          <td class="showBtnBox"><button class="mx-1"><%= link_to "詳細", polish %></button></td>
          <td class="editBtnBox"><button class="mx-1"><%= link_to "編集", edit_polish_path(polish) %></button></td>
          <td class="deleteBtnBox"><button class="mx-1"><%= link_to "削除", polish ,method: :delete, data: {confirm: "削除します。この処理は取り消せません。"} %></button></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

        
</div>

app/views/polishes/new.html.erb
<div class="container mb-5">


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 polishesTitle">
    <div class="row">
      <div class="pageTitle col-sm-5">
      <h1>新規精米の登録</h1>
      </div>
      
      <div class="newBtnBox col-sm-7 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to '精米一覧へ戻る', polishes_path %>
 
      </button>
  </div>
  </div>
</div>

<div class="container">


<h1>新規精米の登録</h1>

<%= form_for(@polish) do |f| %>

  <div class="field">
    <%= f.label :精米日 %><br>
    <%= f.datetime_select :polish_day %>
  </div>
  
  <div class="field">
    <%= f.label :合計使用量（袋） %><br>
    <%= f.number_field :polish_amount_total, :step => 0.5 %>
  </div>

  <div class="field">
    <%= f.label :メモ（玄米で出荷する場合はこちらに“玄米”と記入） %><br>
    <%= f.text_area :polish_memorandum %>
  </div>

<hr>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>内訳−１</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_1_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_1_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_1_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_1_amount, :step => 0.5 %>
    </div>
    </div>
    <div class="col-sm-4">
      <h3>内訳−２</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_2_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_2_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_2_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_2_amount, :step => 0.5 %>
    </div>

    </div>
    <div class="col-sm-4">
      <h3>内訳−３</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_3_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_3_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_3_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_3_amount, :step => 0.5 %>
    </div>
    </div>
  </div>
</div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>内訳−４</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_4_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_4_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_4_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_4_amount, :step => 0.5 %>
    </div>
    </div>
    <div class="col-sm-4">
      <h3>内訳−５</h3>
    <div class="field">
      <%= f.label :生産者id %><br>
      <%= f.collection_select(:polish_5_farmer_id, @stocks, :id, :stock_brand, {prompt: "生産者を選択"} )%>
      </div>
        <div class="field">
      <%= f.label :生産者 %><br>
      <%= f.collection_select(:polish_5_farmer, @stocks, :stock_brand, :stock_brand, {prompt: "生産者を選択"} )%>
    </div>
    <div class="field">
      <%= f.label :銘柄 %><br>
      <%= f.collection_select(:polish_5_brand, @stocks, :stock_brand, :stock_brand, {prompt: "銘柄を選択"}, {class: "hoge"} )%>
    </div>
    <div class="field">
      <%= f.label :使用量（袋） %><br>
      <%= f.number_field :polish_5_amount, :step => 0.5 %>
    </div>

    </div>
    <div class="col-sm-4">
    </div>
  </div>
</div>


<br>
<div class="actions">
  <%= f.submit "新規精米の登録"%>
</div>
<% end %>


</div>
</div>

app/views/polishes/show.html.erb
<div class="container mb-5">
<p id="notice"><%= notice %></p>


<div class="mainBox pb-3 shadow-sm">
  <div class="pageHeader container shadow-sm mb-4 polishesTitle">
    <div class="row">
      <div class="pageTitle col-sm-4">
      <h1>精米の詳細情報</h1>
      </div>

      <div class="newBtnBox col-sm-8 text-right">
      <button class="newBtnSales m-2 ">
        <%= link_to "精米一覧へ戻る" , polishes_path %>
      </button>
      <button class="newBtnSales m-2 ">
        <%= link_to "編集" , edit_polish_path(@polish) %> 
      </button>
      </div>
  </div>
</div>

<div class="container">
<p class="bg-light pl-2"> 精米ID：<%= @polish.id %> </p>

<h2> 精米日：<%= @polish.polish_day.strftime("%m月%d日") %> </h2>
<p class="strong" style="font-size:24px"> 精米数（袋）：<%= @polish.polish_amount_total %>
<p class="strong" style="font-size:24px"> 精米メモ： 
<textarea cols="30" rows="3"><%= @polish.polish_memorandum %></textarea></p>
<hr>
<div class="polish_breakdown">
    <h2>　内訳　</h2>
    <hr>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>内訳−１</h3>
       <p> 生産者id：<%= @polish.polish_1_farmer_id %> </p>
       <p> 生産者名：<%= @polish.polish_1_farmer %> </p>
       <p> 銘柄：<%= @polish.polish_1_brand %> </p>
       <p>使用数（袋）：<%= @polish.polish_1_amount %>　</p>

    </div>
    <div class="col-sm-4">
    <h3>内訳−２</h3>
      <p> 生産者id：<%=@polish.polish_2_farmer_id %> </p>
      <p> 生産者名：<%= @polish.polish_2_farmer %> </p>
      <p> 銘柄：<%= @polish.polish_2_brand %> </p>
      <p>使用数（袋）：<%= @polish.polish_2_amount %>　</p>
    </div>
    <div class="col-sm-4">
    <h3>内訳−３</h3>
      <p> 生産者id：<%= @polish.polish_3_farmer_id %> </p>
      <p> 生産者名：<%= @polish.polish_3_farmer %> </p>
      <p> 銘柄：<%= @polish.polish_3_brand %> </p>
      <p>使用数（袋）：<%= @polish.polish_3_amount %>　</p>
    </div>
  </div>
</div>

<hr>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
    <h3>内訳−４</h3>
      <p> 生産者id：<%= @polish.polish_4_farmer_id %> </p>
      <p> 生産者名：<%= @polish.polish_4_farmer %> </p>
      <p> 銘柄：<%= @polish.polish_4_brand %> </p>
      <p>使用数（袋）：<%= @polish.polish_4_amount %>　</p>
    </div>
    <div class="col-sm-4">
    <h3>内訳−５</h3>
      <p> 生産者id：<%= @polish.polish_5_farmer_id %> </p>
      <p> 生産者名：<%= @polish.polish_5_farmer %> </p>
      <p> 銘柄：<%= @polish.polish_5_brand %> </p>
      <p>使用数（袋）：<%= @polish.polish_5_amount %>　</p>
    </div>
    <div class="col-sm-4">
    </div>
  </div>


<p> 備考：<%= @polish.polish_memorandum %> </p>



</div>
</div>