config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'sales#index' 

  resource :mypage

  get 'item_sales/create'
  get 'item_sales/destroy'
  get 'stock_polishes/create'
  get 'stock_polishes/destroy'
  # get "/" => "home#top"


  resources :sales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :farmers
  # resources :stocks
  resources :stocks do
    resource :stock_polishes, only: [:create, :destroy]
  end

  resources :polishes
  # resources :items
  resources :items do
    resource :item_sales, only: [:create, :destroy]
  end
  resources :cliants

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliant.rb
class Cliant < ApplicationRecord
    has_many :sales
end

app/models/farmer.rb
class Farmer < ApplicationRecord

    has_many :stocks

end

app/models/item.rb
class Item < ApplicationRecord


    has_many :item_sales
    has_many :sales, through: :item_sales

end

app/models/item_sale.rb
class ItemSale < ApplicationRecord
    
    belongs_to :sale
    belongs_to :item

end

app/models/polish.rb
class Polish < ApplicationRecord

    # # 使用した玄米の合計
    # def self.sumpolish  
    #     sum(:polish_amount_total)
    # end

    

    has_many :stock_polishes
    has_many :stocks, through: :stock_polishes
    
    has_many :sales

end

app/models/sale.rb
class Sale < ApplicationRecord

    belongs_to :polilsh,optional: true
    belongs_to :cliant,optional: true

    has_many :item_sales
    has_many :items, through: :item_sales
    

    validates :is_done, inclusion:{in: [true, false]}
    with_options presence: true do
        validates :seller_name
        validates :job_type
        validates :cliant_id
        validates :cliant_name
        validates :item_id
        validates :item_name
        validates :sale_item_count
        validates :sale_item_amount
        # validates :polish_id
    end

end

app/models/stock.rb
class Stock < ApplicationRecord

    # 仕入れの合計
    def self.sumstock  
        sum(:stock_purchased_amount)
        #Stock.sumでも可
      end

    # 使用した在庫の合計
      def self.sumusedstock  
        sum(:stock_used_amount)
      end

    # 現在個数
    def self.sumpresentstock  
        self.sumstock-self.sumusedstock
      end


    belongs_to :farmer

    has_many :stock_polishes
    has_many :polishes, through: :stock_polishes    
    
end

app/models/stock_polish.rb
class StockPolish < ApplicationRecord

    belongs_to :stock
    belongs_to :polish

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cliants_helper.rb
module CliantsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_sales_helper.rb
module ItemSalesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/polishes_helper.rb
module PolishesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom text-center">
  <nav>
    <span>
      <p class="mb-0">©2019 M:e</p>
    </span>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiceManagerG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="mb-3 ">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top shadow-sm py-3">
    <img src="/seimaiApp_logo.jpg" alt="ロゴマーク" width="200px">

      <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarsDefault">
            <ul class="navbar-nav mr-auto mt-2 ml-3">
              <li class="nav-item ">
                <button type="button" class="headerBtn btn btn-lg mx-3 poilshBtn">
                  <%= link_to '精米一覧', polishes_path ,class:"headerTitle" %>
                </button>
              </li>
              <li class="nav-item ">
                <button type="button" class="headerBtn btn btn-lg mx-3 jobBtn">
                  <%= link_to 'Job一覧', sales_path ,class:"headerTitle" %>
                </button>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle btn btn-sm ml-3 text-light dropMenu" href="tutorial.html" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">管理メニュー</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown01">
                      <span class="dropdown-item"><%= link_to '商品 一覧', items_path ,class:"headerDropdownTitle"%></span>
                      <span class="dropdown-item"><%= link_to '顧客一覧', cliants_path ,class:"headerDropdownTitle"%></span>
                      <span class="dropdown-item"><%= link_to '在庫一覧', stocks_path ,class:"headerDropdownTitle"%></span>
                      <span class="dropdown-item"><%= link_to '生産者一覧', farmers_path ,class:"headerDropdownTitle"%></span>
                    </div>
                </li>
            </ul>
          </div>      
          
          <strong> ユーザーID:<%= current_user.id %> </strong>

          <div>
            <button type="button" class="headerBtn btn btn-lg mx-3 logoutBtn">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete ,class:"headerTitle"  %>
            </button>
          </div>
        
      <% end %>
    </nav>

  </header>

    <%# devise用アラート   %>
    <div class="container">
      <div class="time-limit">
        <span class="notice"><%= notice %></span>
        <span class="alert"><%= alert %></span>
      </div>
    </div>


    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>